// do not edit; automatically generated by 'make testconfig' in vhci-hcd sourcedir
#define USB_VHCI_HCD_VERSION "1.15"
#define USB_VHCI_HCD_DATE "2015-12-23"
#define USB_VHCI_IOCIFC_VERSION "1.15"
#define USB_VHCI_IOCIFC_DATE USB_VHCI_HCD_DATE
//#define OLD_GIVEBACK_MECH
//#define OLD_DEV_BUS_ID
//#define NO_DEV_INIT_NAME
//#define NO_HAS_TT_FLAG
// end of file
